import csv,collections,hashlib,subprocess,re
S='source/'
CN=S+'Uniform-Crime-Reports-Part-I-Crimes-1963-2024.pdf'
RT=S+'Uniform-Crime-Reports-Part-I-Crimes-1963-2024-by-Population.pdf'
CR=S+'nashville-fatal-crashes-filtered-2026-09-29.redacted.csv'
sha=lambda p:hashlib.sha256(open(p,'rb').read()).hexdigest()
def pdfrows(p):
    out={}
    for pg in (1,2):
        t=subprocess.check_output(['pdftotext','-layout','-f',str(pg),'-l',str(pg),p,'-'],text=True)
        for ln in t.splitlines():
            m=re.match(r'\s*((?:19|20)\d\d)\*?\s',ln)
            if m and len(ln.replace('*','').split())==11: out[m.group(1)]=(pg,' '.join(ln.replace('*','').split()))
    return out
cn,rt=pdfrows(CN),pdfrows(RT)
# crash csv: byte offsets of each year's first/last data row
raw=open(CR,'rb').read(); off=0; yr=collections.OrderedDict(); rows=[]
lines=raw.split(b'\n')
data=csv.DictReader(open(CR,newline='',encoding='utf-8'))
rows=list(data)
by=collections.defaultdict(lambda:dict(crashes=0,deaths=0,ped=0,hr=0))
for r in rows:
    y=r['Date'][:4];n=int(r['Fatalities'] or 0);b=by[y]
    b['crashes']+=1;b['deaths']+=n
    if 'pedestrian' in r['Crash Type']:b['ped']+=n
    if r['Hit and Run']=='Yes':b['hr']+=n
W=[]
W.append(f"""# MNPD / Nashville: violent crime vs. road safety vs. enforcement

Purpose: one index of facts, each pointing to the bytes it came from, so the three trendlines
can be compared: (A) violent crime, (B) road deaths, (C) roadside stops by police.

**Status of C: no traffic-stop data is in this folder.** Nothing below measures how many stops
MNPD makes. Do not infer a stop trend from A or B. See section C at the end.

## Sources (bytes are in `source/`, hashes are sha256)
| id | file | sha256 | what it is |
|---|---|---|---|
| CNT | `{CN}` | `{sha(CN)}` | MNPD UCR Part I offense counts, 1963-2024, pp.1-2. Footer: counts from MNPD ARMS, pulled 5/29/2025. |
| RATE | `{RT}` | `{sha(RT)}` | Same, per 100,000, pp.1-2. |
| CRASH | `{CR}` | `{sha(CR)}` | Nashville fatal crashes, {len(rows)} rows, {min(r['Date'] for r in rows)} to {max(r['Date'] for r in rows)}. Public copy REDACTED: columns Victim Names, Victim Ages, Housing Statuses removed from the original (original sha256 dc99b1aa8110eebc70ec3ed550d05850f7a7ff2c3960039ac5584ca5a4c084c7); no number below uses them. Named "filtered"; who filtered it and by what rule is NOT recorded here. |

Derived files: `mnpd_ucr_counts_1963_2024.csv` (from CNT), `mnpd_ucr_rates_per100k_1963_2024.csv`
(from RATE). Both made by `pdftotext -layout | tr -d '*,' | awk` with no model in the loop.
This README is generated by `build_readme.py`; rerun it to reproduce every number below.

## A. Violent crime (CNT p.2 / RATE p.2; column order: year total violent property homicide rape robbery agg_assault burglary larceny auto_theft)
Comparability break: the `*` on 2012 marks MNPD adopting the new FBI rape definition a year early;
rape counts before 2012 are a different series. Homicide/agg-assault definitions are not stated in the PDF.

| year | violent (count) | homicide | agg assault | robbery | violent per 100k | source line in CNT (page: exact text) |
|---|---|---|---|---|---|---|""")
for y in map(str,range(2010,2025)):
    pg,l=cn[y];f=l.split();g=rt[y][1].split()
    W.append(f"| {y} | {f[2]} | {f[4]} | {f[7]} | {f[6]} | {g[2]} | p{pg}: `{l}` |")
W.append("""
RATE source lines for the same years: `pdftotext -layout -f 2 -l 2 source/Uniform-Crime-Reports-Part-I-Crimes-1963-2024-by-Population.pdf -` and grep the year.
Full 1963-2024 series: the two derived CSVs.

## B. Fatal crashes (CRASH; recomputed from the CSV, columns `Date`, `Fatalities`, `Crash Type`, `Hit and Run`)
"Pedestrian deaths" = rows whose `Crash Type` contains "pedestrian" (includes `pedestrian; vehicle`).
2017 starts 2017-01-13 and 2026 ends 2026-09-27, so those two years are partial. Whether the file is
complete for any year is unverified.

| year | fatal crashes | deaths | pedestrian deaths | deaths in hit-and-run |
|---|---|---|---|---|""")
for y in sorted(by):
    b=by[y];W.append(f"| {y} | {b['crashes']} | {b['deaths']} | {b['ped']} | {b['hr']} |")
W.append(f"""
Byte source: whole-file sha256 above; row order is newest first. Each row's own bytes carry its
`News Links` column, which is the upstream source for that crash (e.g. WKRN, nashville.gov).

## Reading A and B side by side (what the bytes support, nothing more)
Violent count peaked 2022 (9,060) and fell in 2023-2024 (CNT). Recorded road deaths peaked 2023
(136) and were 116 in 2024 (CRASH). Pedestrian deaths were 24-41 a year in 2017-2020 and 24-44 in 2021-2025, with no
clear step (CRASH). Those are separate series, not a cause. Nothing here says whether stops
changed, because no stops series is present.

## C. Roadside stops by police: MISSING
Needed to test the hypothesis, none present in this folder or in ~/Downloads:
- MNPD traffic stop counts by year (ideally by stop reason and by outcome: warning/citation/arrest).
- Citation counts by year (Davidson County General Sessions / MNPD).
- Sworn officer headcount and traffic-division staffing by year, to separate fewer stops from fewer officers.
- Tennessee TITAN/crash-report totals or NHTSA FARS for Davidson County, to cross-check CRASH's completeness.
Once a file is added under `source/`, add it to the Sources table with its sha256 and cite lines as above.

## Not sourced
`2026.6.29_Policing_Public_Safety.pdf` (in Downloads) is a research bibliography; it contains no
Nashville stop or crash figures, so it is not used here. `UCR1963-2023ByPopulation.pdf` is an older
edition of RATE (pull dated 7/17/2024) and is not used.
""")
open('README.md','w').write('\n'.join(W))
